application:
  port: 8083

spring:
  application:
    name: Api-Gateway

  eureka:
    client:
      service-url:
        defaultZone: http://localhost:8761/eureka

com:
  retailmate:
    ms:
      configurations:
        gateway:
          service:
            names:
              Product-Service: "http://localhost:8083/"
              Order-Service: "http://localhost:8084/"
              Billing-Service: "http://localhost:8085/"
              Inventory-Service: "http://localhost:8086/"
