application:
  port: 8083

spring:
  application:
    name: Api-Gateway

  eureka:
    client:
      service-url:
        defaultZone: http://localhost:8761/eureka

com:
  retailmate:
    ms:
      configurations:
        gateway:
          services:
            PRODUCT-SERVICE:
              uri: lb://PRODUCT-SERVICE
              predicate:
                Path=/api/products/**
            ORDER-SERVICE:
              uri: lb://ORDER-SERVICE
              predicate: Path=/api/orders/**
            BILLING-SERVICE:
              uri: lb://BILLING-SERVICE
              predicate: Path=/api/billing/**
            INVENTORY-SERVICE:
              uri: lb://INVENTORY-SERVICE
              predicate: Path=/api/inventory/**
