server:
  port: 8082
application:
  name: Product-Order-Service
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/
    username: root
    password: RajpuT@123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
